version: 2.1

executors:
  dotnet_executor:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:7.0
    working_directory: ~/project

jobs:
  build:
    executor: dotnet_executor
    steps:
      - checkout

      - run:
          name: Restore NuGet packages
          command: dotnet restore

      - run:
          name: Build the project
          command: dotnet build --configuration Release

      - run:
          name: Run Playwright Install
          command: dotnet build-server shutdown && npx playwright install

      - run:
          name: Run Tests
          command: dotnet test --filter "TestCategory=Playwright"

workflows:
  version: 2
  test:
    jobs:
      - build
