---
version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.1
executors:
  dotnet_executor:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0
    working_directory: ~/project
jobs:
  build:
    executor: dotnet_executor
    steps:
      - checkout
      - browser-tools/install-chrome
      - run:
          name: Restore NuGet packages
          command: dotnet restore
      - run:
          name: Build the project
          command: dotnet build --configuration Debug
      - run:
          name: Run Tests
          command: dotnet test
workflows:
  version: 2
  test:
    jobs:
      - build
